### ISSUE TITLE
编译优化放在混淆前面

### ISSUE THREAD

**Issue by 1136117475** [DreamSoule/ollvm17#18]
能不能把混淆放在O优化的后面，不然开了O3优化再开混淆，混淆强度大大降低，先进行优化再进行混淆🥺

**Comment by 1136117475** [comment]
> 能不能把混淆放在O优化的后面，不然开了O3优化再开混淆，混淆强度大大降低，先进行优化再进行混淆🥺

**Comment by JiaPai12138** [comment]
只能关优化了好像
