### ISSUE TITLE
内核模式支持?

### ISSUE THREAD

**Issue by kkptm** [DreamSoule/ollvm17#19]
如何支持内核模式的编译?

**Comment by DreamSoule** [comment]
用[LLVM-MSVC](https://github.com/backengineering/llvm-msvc)项目把混淆加进去就能编译可以正常加载的windows驱动文件了

**Comment by xw1369** [comment]
> 用[LLVM-MSVC](https://github.com/backengineering/llvm-msvc)项目把图示加进去就能编译可以正常加载的windows驱动文件了

有些编译出来的驱动不能加载,用LLVM-MSVC编译出来的可以加载.是项目配置有问题吗
